# Generated by Django 5.0.1 on 2024-01-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
